library(dplyr)
mech <- read.csv('MechaCar_mpg.csv',check.names = F,stringsAsFactors = F)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mech)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mech)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mech))
coils <- read.csv('Suspension_Coil.csv',check.names = F,stringsAsFactors = F)
total_summary <- coils %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI), .groups = 'keep')
lot_summary <- coils %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI), .groups = 'keep')
t.test(x=coils$PSI,mu=1500) 
sub1  <-  subset(coils, Manufacturing_Lot=='Lot1')
t.test(x=sub1$PSI,mu=1500)
sub2  <-  subset(coils, Manufacturing_Lot=='Lot2')
t.test(x=sub2$PSI,mu=1500)
sub3  <-  subset(coils, Manufacturing_Lot=='Lot3')
t.test(x=sub3$PSI,mu=1500)